name: Lukkit
version: @version@
main: dev.artex.lukkit.Main
api-version: 1.13
load: STARTUP
authors: [jammehcow, AL_1, matthulk]
description: A Lua wrapper for writing Bukkit plugins
website: https://lukkit.net
