name: Lukkit
version: @version@
main: net.lukkit.lukkit.Main
api-version: @mcVersion@
load: STARTUP
authors: [jammehcow, AL_1, matthulk]
description: A Lua wrapper for writing Bukkit plugins
website: @lukkitWeb@
